on:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}
env:
  TERM: xterm-256color
  FORCE_COLOR: 1
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: lts/*, registry-url: 'https://registry.npmjs.org' }
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
      - run: pnpm release --yes
