on:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}
env:
  TERM: xterm-256color
  FORCE_COLOR: 1
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: mise
        uses: jdx/mise-action@v2
      - name: install
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm build
      - name: test
        run: pnpm test
      - name: publish
        run: npx rev publish
