on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

env:
  TERM: xterm-256color
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Corepack
        run: |
          set -e
          corepack enable

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore
        run: |
          set -e
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          set -e
          pnpm build
        
      - name: Test
        run: |
          set -e
          pnpm test

      # - name: Publish
      #   run: |
      #     set -e
      #     pnpm config --location=project set //registry.npmjs.org/:_authToken '${NPM_TOKEN}'
      #     pnpm -r publish --no-git-checks
      #   env:
      #     NPM_TOKEN: ${{secrets.NPM_TOKEN}}
